#!/bin/bash
# DataWarden2 - Interactive Setup Script
# Creates virtual environment, installs dependencies, writes config

set -e

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║           DataWarden2 - Interactive Setup                   ║"
echo "║      Enterprise Duplicate Finder & Data Governance          ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

# Get venv name
read -p "Venv-Name eingeben (Standard: .venv): " VENV_NAME
VENV_NAME=${VENV_NAME:-.venv}

# Get venv path
read -p "Venv-Pfad eingeben (Standard: aktuelles Verzeichnis): " VENV_PATH
VENV_PATH=${VENV_PATH:-.}

FULL_PATH="$VENV_PATH/$VENV_NAME"

echo ""
echo "Erstelle Virtual Environment unter: $FULL_PATH"
echo ""

# Check Python version
PYTHON_VERSION=$(python3 --version 2>&1 | cut -d' ' -f2)
echo "Python Version: $PYTHON_VERSION"

# Check minimum Python 3.11
PYTHON_MAJOR=$(echo $PYTHON_VERSION | cut -d. -f1)
PYTHON_MINOR=$(echo $PYTHON_VERSION | cut -d. -f2)
if [ "$PYTHON_MAJOR" -lt 3 ] || [ "$PYTHON_MAJOR" -eq 3 -a "$PYTHON_MINOR" -lt 11 ]; then
    echo "⚠️  WARNUNG: Python 3.11+ wird empfohlen. Aktuelle Version: $PYTHON_VERSION"
    read -p "Trotzdem fortfahren? (j/N): " CONTINUE
    if [[ ! "$CONTINUE" =~ ^[Jj]$ ]]; then
        echo "Abbruch."
        exit 1
    fi
fi

# Create venv
python3 -m venv "$FULL_PATH"

# Activate and upgrade pip
source "$FULL_PATH/bin/activate"
pip install --upgrade pip

# Install requirements
echo ""
echo "Installiere Dependencies aus requirements.txt..."
pip install -r requirements.txt

# Deactivate
deactivate

# Write config file for start.sh / update.sh
mkdir -p config
cat > config/paths.conf <<EOF
# Auto-generated by setup.sh
VENV_DIR="$FULL_PATH"
EOF

# Initialize git if not already
if [ ! -d ".git" ]; then
    git init
    git add .
    git commit -m "Initial commit: DataWarden2 project structure"
    echo "📁 Git Repository initialisiert"
fi

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  ✅ Setup abgeschlossen!                                     ║"
echo "║                                                              ║"
echo "║  Virtual Environment: $FULL_PATH"
echo "║  Config geschrieben: config/paths.conf"
echo "║                                                              ║"
echo "║  Starten mit: ./start.sh                                     ║"
echo "║  Aktualisieren mit: ./update.sh                              ║"
echo "╚══════════════════════════════════════════════════════════════╝"